
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_local
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}  # Le mot de passe de votre connection string
    ports:
      - "1433:1433"
    user: root
    volumes:
      - sqlserver_data:/var/opt/mssql/data

    restart: always

volumes:
  sqlserver_data:
